### ISSUE TITLE
该项目还在继续吗

### ISSUE THREAD

**Issue by wrfgup** [zzttqu/genshin-auto#5]
感觉挺有意思的，虽然很难实现。先前我就是因为原神太肝了退的坑，现在突然想自己写个脚本做每日，挖矿啥的。

**Comment by zzttqu** [comment]
暂时搁置了这个项目，如果有时间的话会继续充实的。每日任务做起来感觉有点麻烦，寻路不好实现，不过挖矿相关的脚本B站好像有视频，以后会借鉴的。

**Comment by wrfgup** [comment]
确实 感觉寻路像自动驾驶 难度很大 但是无意中看到了这个项目https://github.com/GengGode/GenshinImpact_AutoTrack_DLL，感觉可以拿过来做轮子用

**Comment by zzttqu** [comment]
十分感谢，第一个GitHub公开仓库能有人看到很激动。以后有时间会一点一点加东西的。当时做这个东西主要是看到了b站那个钓鱼的很火，就看了一看，之前做的脚本的问题一直是没法把操作反馈回原神里面，直到看到可以用win32的api来操作。
